/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;
import Modelo.*;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author cabre
 */
public class frmSistemaClientes extends javax.swing.JFrame {
    static Cliente clie;
    static boolean sesion;
    /**
     * Creates new form frmSistema
     */
    public frmSistemaClientes() {
        initComponents();
        muestraFoto();
        this.setLocationRelativeTo(this);
        this.setTitle("Tienda PetShop");
    }
    
    void muestraFoto(){
        String ruta = new File("src").getAbsolutePath();
        ruta = ruta+"/main/java/Imagenes/petShop.jpg";
        ImageIcon img = new ImageIcon(ruta);
        Image imgsc = img.getImage().getScaledInstance(lbFoto.getWidth(), lbFoto.getHeight(), Image.SCALE_SMOOTH);
        lbFoto.setIcon(new ImageIcon(imgsc));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        lbFoto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jmIniciarSesion = new javax.swing.JMenuItem();
        jmProducto = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenu();
        jmcarrito = new javax.swing.JMenuItem();
        jmRegistroCompras = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmAyuda = new javax.swing.JMenuItem();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO A PET SHOP");

        lbFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jmArchivo.setText("Archivo");

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jmArchivo.add(jmSalir);

        jmIniciarSesion.setText("Iniciar sesión");
        jmIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIniciarSesionActionPerformed(evt);
            }
        });
        jmArchivo.add(jmIniciarSesion);

        jMenuBar1.add(jmArchivo);

        jmProducto.setText("Producto");
        jmProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProductoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ver Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmProducto.add(jMenuItem1);

        jMenuBar1.add(jmProducto);

        menuCompra.setText("Compra");
        menuCompra.setEnabled(false);
        menuCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompraActionPerformed(evt);
            }
        });

        jmcarrito.setText("Ver carrito");
        jmcarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcarritoActionPerformed(evt);
            }
        });
        menuCompra.add(jmcarrito);

        jmRegistroCompras.setText("Ver compras");
        jmRegistroCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegistroComprasActionPerformed(evt);
            }
        });
        menuCompra.add(jmRegistroCompras);

        jMenuBar1.add(menuCompra);

        jMenu4.setText("Ayuda");

        jmAyuda.setText("Acerca de");
        jmAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAyudaActionPerformed(evt);
            }
        });
        jMenu4.add(jmAyuda);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jmProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProductoActionPerformed
        //
    }//GEN-LAST:event_jmProductoActionPerformed

    private void jmAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAyudaActionPerformed
        frmAcercade objfrmAcercade = new frmAcercade();
        objfrmAcercade.setVisible(true);
    }//GEN-LAST:event_jmAyudaActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIniciarSesionActionPerformed
        if(sesion == false){
            frmRegisterCliente objfrmRegisterCliente = new frmRegisterCliente();
            objfrmRegisterCliente.setVisible(true);
        } else{
            clie = new Cliente();
            jmIniciarSesion.setText("Iniciar sesión");
            JOptionPane.showMessageDialog(null, "Sesion cerrada");
            sesion = false;
        }
    }//GEN-LAST:event_jmIniciarSesionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmProductos objfrmProductos = new frmProductos();
        objfrmProductos.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmRegistroComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegistroComprasActionPerformed
        if(sesion == false){
            JOptionPane.showMessageDialog(null, "Debe iniciar sesión");
        } else{
            frmClienteCompras objfrmClienteCompras = new frmClienteCompras();
            objfrmClienteCompras.setVisible(true);
        }
    }//GEN-LAST:event_jmRegistroComprasActionPerformed

    private void jmcarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcarritoActionPerformed
        if(sesion == false){
            JOptionPane.showMessageDialog(null, "Debe iniciar sesión");
        } else{
            frmCarrito objfrmCarrito = new frmCarrito();
            objfrmCarrito.setVisible(true);
        }
    }//GEN-LAST:event_jmcarritoActionPerformed

    private void menuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompraActionPerformed
        if(sesion == false){
            JOptionPane.showMessageDialog(null, "Debe iniciar sesión");
        }
    }//GEN-LAST:event_menuCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSistemaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSistemaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSistemaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSistemaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSistemaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenuItem jmAyuda;
    public static javax.swing.JMenuItem jmIniciarSesion;
    private javax.swing.JMenu jmProducto;
    private javax.swing.JMenuItem jmRegistroCompras;
    private javax.swing.JMenuItem jmSalir;
    private javax.swing.JMenuItem jmcarrito;
    private javax.swing.JLabel lbFoto;
    public static javax.swing.JMenu menuCompra;
    // End of variables declaration//GEN-END:variables
}
