/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Modelo.*;
import Controlador.NegocioCuenta;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author cabre
 */
public class frmSistemaEmpleado extends javax.swing.JFrame {
    static boolean sesion;
    static Empleado Emp;
    /**
     * Creates new form frmSistemaEmpleado
     */
    public frmSistemaEmpleado() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Sistema Empleados Tienda Petshop");
        muestraFoto();
        
    }
    
    void muestraFoto(){
        String ruta = new File("src").getAbsolutePath();
        ruta = ruta+"/main/java/Imagenes/petShop.jpg";
        ImageIcon img = new ImageIcon(ruta);
        Image imgsc = img.getImage().getScaledInstance(lbFoto.getWidth(), lbFoto.getHeight(), Image.SCALE_SMOOTH);
        lbFoto.setIcon(new ImageIcon(imgsc));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jmSesion = new javax.swing.JMenuItem();
        jmVistaCliente = new javax.swing.JMenuItem();
        menuListado = new javax.swing.JMenu();
        jmListaGeneral = new javax.swing.JMenuItem();
        jmListaCambios = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        jmManProductos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmCuentaEmp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel1.setText("SISTEMA PET SHOP");

        jMenu1.setText("Archivo");

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmSalir);

        jmSesion.setText("Iniciar sesión");
        jmSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSesionActionPerformed(evt);
            }
        });
        jMenu1.add(jmSesion);

        jmVistaCliente.setText("Vista Cliente");
        jmVistaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVistaClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmVistaCliente);

        jMenuBar1.add(jMenu1);

        menuListado.setText("Listado");
        menuListado.setEnabled(false);

        jmListaGeneral.setText("Lista General");
        jmListaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaGeneralActionPerformed(evt);
            }
        });
        menuListado.add(jmListaGeneral);

        jmListaCambios.setText("Lista de cambios");
        jmListaCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaCambiosActionPerformed(evt);
            }
        });
        menuListado.add(jmListaCambios);

        jMenuBar1.add(menuListado);

        menuMantenimiento.setText("Mantenimiento");
        menuMantenimiento.setEnabled(false);

        jmManProductos.setText("Productos");
        jmManProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManProductosActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jmManProductos);

        jMenuItem1.setText("Añadir Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jMenuItem1);

        jmCuentaEmp.setText("Cuenta Empleado");
        jmCuentaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCuentaEmpActionPerformed(evt);
            }
        });
        menuMantenimiento.add(jmCuentaEmp);

        jMenuBar1.add(menuMantenimiento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmListaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaGeneralActionPerformed
            frmListas objfrmListaClientes = new frmListas();
            objfrmListaClientes.setVisible(true);
        
    }//GEN-LAST:event_jmListaGeneralActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSesionActionPerformed
        if(sesion == false){
            frmRegisterEmpleado objfrmRegisterEmpleado = new frmRegisterEmpleado();
            objfrmRegisterEmpleado.setVisible(true);
        } else{
            Emp = new Empleado();
            jmSesion.setText("Iniciar sesión");
            JOptionPane.showMessageDialog(null, "Sesion cerrada");
            sesion = false;
        }
    }//GEN-LAST:event_jmSesionActionPerformed

    private void jmManProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManProductosActionPerformed
        
            frmMantenimientoProductos objfrmMantenimientoProductos = new frmMantenimientoProductos();
            objfrmMantenimientoProductos.setVisible(true);
        
    }//GEN-LAST:event_jmManProductosActionPerformed

    private void jmCuentaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCuentaEmpActionPerformed
        
            frmCuentaEmpleado objfrmCuentaEmpleado = new frmCuentaEmpleado();
            objfrmCuentaEmpleado.setVisible(true);
        
    }//GEN-LAST:event_jmCuentaEmpActionPerformed

    private void jmVistaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVistaClienteActionPerformed
        frmSistemaClientes objfrmSistemaClientes = new frmSistemaClientes();
        objfrmSistemaClientes.setVisible(true);
    }//GEN-LAST:event_jmVistaClienteActionPerformed

    private void jmListaCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaCambiosActionPerformed
        frmListaCambios objfrmListaCambios = new frmListaCambios();
        objfrmListaCambios.setVisible(true);
    }//GEN-LAST:event_jmListaCambiosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmAgregarProducto objfrmAgregarProducto = new frmAgregarProducto();
        objfrmAgregarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSistemaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSistemaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSistemaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSistemaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSistemaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmCuentaEmp;
    private javax.swing.JMenuItem jmListaCambios;
    private javax.swing.JMenuItem jmListaGeneral;
    private javax.swing.JMenuItem jmManProductos;
    private javax.swing.JMenuItem jmSalir;
    public static javax.swing.JMenuItem jmSesion;
    private javax.swing.JMenuItem jmVistaCliente;
    private javax.swing.JLabel lbFoto;
    public static javax.swing.JMenu menuListado;
    public static javax.swing.JMenu menuMantenimiento;
    // End of variables declaration//GEN-END:variables
}
